<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{8c7f3494-d62b-4dce-8edb-a017c884dc00}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	{attribute 'OPC.UA.DA':='1'}
	time_info:	FB_TIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[time_info();

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="8" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>