<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="POU" Id="{354f178c-7dbb-4aed-971f-daafe37d283e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU EXTENDS FB_ReadEL6688CoE
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>