<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_NOTT_ICS" Id="{35e04548-ee92-4622-970e-d83afc0b7c18}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_NOTT_ICS
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_NOTT_ICS">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>