<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_NOTT_CRYO_CTRL" Id="{6db86964-7275-49aa-8bde-6c64e8e92208}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_NOTT_CRYO_CTRL
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_NOTT_CRYO_CTRL">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>