<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_NOTT_ICS" Id="{35e04548-ee92-4622-970e-d83afc0b7c18}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_NOTT_ICS
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	
	Delay_Lines:		FB_NOTT_DELAY_LINES;
	
	Shutters:			FB_NOTT_SHUTTERS;
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

Delay_Lines();
Delay_Lines.M_SET_DL_ACTUAL_POS();

Shutters();



]]></ST>
    </Implementation>
    <LineIds Name="FB_NOTT_ICS">
      <LineId Id="18" Count="1" />
      <LineId Id="9" Count="0" />
      <LineId Id="64" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="48" Count="0" />
      <LineId Id="46" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="62" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>