<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{d1f43969-a3b8-40c6-8624-60de23968539}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	{attribute 'OPC.UA.DA' := '1'}
	nOpc_ua_test:		DINT;	
	i AT %I* : UINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nOpc_ua_test := 15220;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>