<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="FB_NOTT_STEPPER_SHUTTER" Id="{2b5f4452-810d-4eb6-9497-660721820ccc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_NOTT_STEPPER_SHUTTER EXTENDS FB_MOTOR
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
SUPER^();]]></ST>
    </Implementation>
    <LineIds Name="FB_NOTT_STEPPER_SHUTTER">
      <LineId Id="10" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>