<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="FB_HMI_CABINETS" Id="{7cfce7ac-44b3-4d04-a8cd-813baf72c575}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HMI_CABINETS EXTENDS FB_HMI_COMPONENT
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HMI_CABINETS">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>