///////////////////////////////////////////////////////////////////////////////
// trkparamsServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_trkparams = 0x3F000000;
#define SRVNAME_TRKPARAMS "trkparams"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_trkparamsCtrkParams = {0x15952e35,0x5679,0x4d71,{0x9f,0x28,0x19,0x6d,0xf1,0x4b,0xbd,0x2e}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_trkParamsParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_C54078A5_7668_499A_8F9F_9F7741190E0F_INCLUDED_)
#define _TC_TYPE_C54078A5_7668_499A_8F9F_9F7741190E0F_INCLUDED_
typedef struct _SlaMappa
{
	double par1;
	double par2;
	double par3;
	double par4;
	double par5;
	double par6;
	double par7;
	double par8;
	double par9;
	double par10;
	double par11;
	double par12;
	double par13;
	double par14;
	double par15;
	double par16;
	double par17;
	double par18;
	double par19;
	double par20;
	double par21;
} SlaMappa, *PSlaMappa;
#endif // !defined(_TC_TYPE_C54078A5_7668_499A_8F9F_9F7741190E0F_INCLUDED_)

#if !defined(_TC_TYPE_E87DD8EA_7465_4059_A5D3_DA46B4FBB7E1_INCLUDED_)
#define _TC_TYPE_E87DD8EA_7465_4059_A5D3_DA46B4FBB7E1_INCLUDED_
typedef struct _SlaAoppa
{
	double par1;
	double par2;
	double par3;
	double par4;
	double par5;
	double par6;
	double par7;
	double par8;
	double par9;
	double par10;
	double par11;
	double par12;
	double par13;
	double par14;
} SlaAoppa, *PSlaAoppa;
#endif // !defined(_TC_TYPE_E87DD8EA_7465_4059_A5D3_DA46B4FBB7E1_INCLUDED_)

#if !defined(_TC_TYPE_049AFE5A_58E6_4FE5_B980_2A0250BE5D02_INCLUDED_)
#define _TC_TYPE_049AFE5A_58E6_4FE5_B980_2A0250BE5D02_INCLUDED_
typedef struct _TrkEnvironment
{
	double temperature;
	double pressure;
	double humidity;
	double lapserate;
} TrkEnvironment, *PTrkEnvironment;
#endif // !defined(_TC_TYPE_049AFE5A_58E6_4FE5_B980_2A0250BE5D02_INCLUDED_)

#if !defined(_TC_TYPE_B20151A0_127E_4FEC_8580_88B0462A0ED6_INCLUDED_)
#define _TC_TYPE_B20151A0_127E_4FEC_8580_88B0462A0ED6_INCLUDED_
typedef struct _TrkSiteConstants
{
	double longitude;
	double latitude;
	double height;
} TrkSiteConstants, *PTrkSiteConstants;
#endif // !defined(_TC_TYPE_B20151A0_127E_4FEC_8580_88B0462A0ED6_INCLUDED_)

#if !defined(_TC_TYPE_54E29DB2_5FB7_4CCE_9241_C355A71CBB91_INCLUDED_)
#define _TC_TYPE_54E29DB2_5FB7_4CCE_9241_C355A71CBB91_INCLUDED_
typedef struct _TrkPolarMotion
{
	double x;
	double y;
} TrkPolarMotion, *PTrkPolarMotion;
#endif // !defined(_TC_TYPE_54E29DB2_5FB7_4CCE_9241_C355A71CBB91_INCLUDED_)

#if !defined(_TC_TYPE_250F9509_3AFF_475A_96D4_FFABBB4AE5B0_INCLUDED_)
#define _TC_TYPE_250F9509_3AFF_475A_96D4_FFABBB4AE5B0_INCLUDED_
typedef struct _TimeInfo
{
	LONGLONG offset;
	SHORT leap_second;
	unsigned char reserved1[2];
	LONG mode;
} TimeInfo, *PTimeInfo;
#endif // !defined(_TC_TYPE_250F9509_3AFF_475A_96D4_FFABBB4AE5B0_INCLUDED_)

#if !defined(_TC_TYPE_082D96CF_EB15_47FF_931F_C8A4BD575526_INCLUDED_)
#define _TC_TYPE_082D96CF_EB15_47FF_931F_C8A4BD575526_INCLUDED_
typedef struct _SlaParams
{
	SlaMappa mappa;
	SlaAoppa aoppa;
} SlaParams, *PSlaParams;
#endif // !defined(_TC_TYPE_082D96CF_EB15_47FF_931F_C8A4BD575526_INCLUDED_)

#if !defined(_TC_TYPE_260AC415_F646_450C_B3D0_7610FCDBAEFA_INCLUDED_)
#define _TC_TYPE_260AC415_F646_450C_B3D0_7610FCDBAEFA_INCLUDED_
typedef struct _CcsData
{
	TrkEnvironment environment;
	TrkSiteConstants site;
	TrkPolarMotion motion;
	double dut;
	double equinox;
	double wavelength;
} CcsData, *PCcsData;
#endif // !defined(_TC_TYPE_260AC415_F646_450C_B3D0_7610FCDBAEFA_INCLUDED_)

typedef struct _trkParamsParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} trkParamsParameter, *PtrkParamsParameter;

typedef struct _trkParamsInputs
{
	TimeInfo TimeInfo;
	CcsData CcsData;
} trkParamsInputs, *PtrkParamsInputs;

typedef struct _trkParamsOutputs
{
	SlaParams SlaParams;
} trkParamsOutputs, *PtrkParamsOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_trkParamsInputs 0
#define ADI_trkParamsOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
