///////////////////////////////////////////////////////////////////////////////
// trkmoduleInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "trkmoduleServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
