<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="FB_HMI_CONTROL_LOOPS" Id="{5023b53e-99b1-4fb5-84ce-f5a08a21ef1f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HMI_CONTROL_LOOPS EXTENDS FB_HMI_COMPONENT
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HMI_CONTROL_LOOPS">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>