///////////////////////////////////////////////////////////////////////////////
// trkmoduleServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_trkmodule = 0x3F000000;
#define SRVNAME_TRKMODULE "trkmodule"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_trkmoduleCtrkModule = {0x6f6a340e,0x378a,0x4fe4,{0xab,0x0d,0xf1,0x5c,0x12,0xdf,0xef,0x0c}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_trkModuleParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_878E358B_EBF9_48B5_B297_E48D5F16F23F_INCLUDED_)
#define _TC_TYPE_878E358B_EBF9_48B5_B297_E48D5F16F23F_INCLUDED_
typedef struct _TrkComputation
{
	double lst;
	double pa;
	double pa_deg;
	double alt;
	double alt_deg;
	double ha;
	double az;
	double az_deg;
	double rotation;
	double rotation_deg;
	double ra;
	double dec;
} TrkComputation, *PTrkComputation;
#endif // !defined(_TC_TYPE_878E358B_EBF9_48B5_B297_E48D5F16F23F_INCLUDED_)

#if !defined(_TC_TYPE_92413486_570E_408C_988A_C47B1BF3BCB2_INCLUDED_)
#define _TC_TYPE_92413486_570E_408C_988A_C47B1BF3BCB2_INCLUDED_
typedef struct _TrkMeanCoordinates
{
	double alpha;
	double delta;
	double epoch;
	double equinox;
	double pma;
	double pmd;
	double radvel;
	double parallax;
} TrkMeanCoordinates, *PTrkMeanCoordinates;
#endif // !defined(_TC_TYPE_92413486_570E_408C_988A_C47B1BF3BCB2_INCLUDED_)

#if !defined(_TC_TYPE_1ECB25A9_3E99_4ED7_B581_B4994614436E_INCLUDED_)
#define _TC_TYPE_1ECB25A9_3E99_4ED7_B581_B4994614436E_INCLUDED_
typedef struct _TrkApparentCoordinates
{
	double alpha;
	double delta;
} TrkApparentCoordinates, *PTrkApparentCoordinates;
#endif // !defined(_TC_TYPE_1ECB25A9_3E99_4ED7_B581_B4994614436E_INCLUDED_)

#if !defined(_TC_TYPE_D15ACD2E_6AAB_4988_8552_571C5D599215_INCLUDED_)
#define _TC_TYPE_D15ACD2E_6AAB_4988_8552_571C5D599215_INCLUDED_
typedef struct _TrkObservedCoordinates
{
	double alpha;
	double delta;
	double ha;
	double zd;
	double az;
} TrkObservedCoordinates, *PTrkObservedCoordinates;
#endif // !defined(_TC_TYPE_D15ACD2E_6AAB_4988_8552_571C5D599215_INCLUDED_)

#if !defined(_TC_TYPE_1C5E8191_65E5_4B10_A3D9_1D62C87554FF_INCLUDED_)
#define _TC_TYPE_1C5E8191_65E5_4B10_A3D9_1D62C87554FF_INCLUDED_
typedef struct _TrkPomTerms
{
	double ia;
	double ie;
	double tf;
	unsigned char reserved1[8];
	double tx;
	double an;
	double aw;
	double npae;
	double ca;
} TrkPomTerms, *PTrkPomTerms;
#endif // !defined(_TC_TYPE_1C5E8191_65E5_4B10_A3D9_1D62C87554FF_INCLUDED_)

#if !defined(_TC_TYPE_FBFA93C8_00C5_4B25_A578_D1C6B8CCAC16_INCLUDED_)
#define _TC_TYPE_FBFA93C8_00C5_4B25_A578_D1C6B8CCAC16_INCLUDED_
typedef struct _TrkMappa
{
	double par1;
	double par2;
	double par3;
	double par4;
	double par5;
	double par6;
	double par7;
	double par8;
	double par9;
	double par10;
	double par11;
	double par12;
	double par13;
	double par14;
	double par15;
	double par16;
	double par17;
	double par18;
	double par19;
	double par20;
	double par21;
} TrkMappa, *PTrkMappa;
#endif // !defined(_TC_TYPE_FBFA93C8_00C5_4B25_A578_D1C6B8CCAC16_INCLUDED_)

#if !defined(_TC_TYPE_4C404B50_9D37_4C1A_865B_060330FE7FD8_INCLUDED_)
#define _TC_TYPE_4C404B50_9D37_4C1A_865B_060330FE7FD8_INCLUDED_
typedef struct _TrkAoppa
{
	double par1;
	double par2;
	double par3;
	double par4;
	double par5;
	double par6;
	double par7;
	double par8;
	double par9;
	double par10;
	double par11;
	double par12;
	double par13;
	double par14;
} TrkAoppa, *PTrkAoppa;
#endif // !defined(_TC_TYPE_4C404B50_9D37_4C1A_865B_060330FE7FD8_INCLUDED_)

#if !defined(_TC_TYPE_93C25DB9_32AE_49ED_8BC0_F208B1DA179C_INCLUDED_)
#define _TC_TYPE_93C25DB9_32AE_49ED_8BC0_F208B1DA179C_INCLUDED_
typedef struct _TimeInfo
{
	LONGLONG offset;
	LONG leap_second;
	LONG mode;
} TimeInfo, *PTimeInfo;
#endif // !defined(_TC_TYPE_93C25DB9_32AE_49ED_8BC0_F208B1DA179C_INCLUDED_)

#if !defined(_TC_TYPE_96C6783B_2218_418F_B568_802C2EF6523C_INCLUDED_)
#define _TC_TYPE_96C6783B_2218_418F_B568_802C2EF6523C_INCLUDED_
typedef struct _TrkTime
{
	LONGLONG dc_time;
	LONG mode;
	unsigned char reserved1[4];
} TrkTime, *PTrkTime;
#endif // !defined(_TC_TYPE_96C6783B_2218_418F_B568_802C2EF6523C_INCLUDED_)

#if !defined(_TC_TYPE_1FF32D32_AF29_41BE_A456_1166D835F7CE_INCLUDED_)
#define _TC_TYPE_1FF32D32_AF29_41BE_A456_1166D835F7CE_INCLUDED_
typedef struct _SlaParams
{
	TrkMappa mappa;
	TrkAoppa aoppa;
} SlaParams, *PSlaParams;
#endif // !defined(_TC_TYPE_1FF32D32_AF29_41BE_A456_1166D835F7CE_INCLUDED_)

#if !defined(_TC_TYPE_C66C44A6_9457_425A_908C_27053AE306A5_INCLUDED_)
#define _TC_TYPE_C66C44A6_9457_425A_908C_27053AE306A5_INCLUDED_
typedef struct _TrackingData
{
	TrkComputation computation;
	TrkApparentCoordinates apparent;
	TrkObservedCoordinates observed;
	TrkTime utctime;
} TrackingData, *PTrackingData;
#endif // !defined(_TC_TYPE_C66C44A6_9457_425A_908C_27053AE306A5_INCLUDED_)

#if !defined(_TC_TYPE_20B39C3A_F540_49EF_8434_28702C07488B_INCLUDED_)
#define _TC_TYPE_20B39C3A_F540_49EF_8434_28702C07488B_INCLUDED_
typedef struct _PointingKernelPositions
{
	double target_observed_altaz[2];
	double current_observed_altaz[2];
	double time_lst;
	double time_tai;
	double time_utc;
	double north_angle;
	double pupil_angle;
	double elevation_direction_angle;
	double radec_at_altaz_at_requested_xy[2];
	double observed_altaz_at_requested_xy[2];
	double parallactic_angle;
} PointingKernelPositions, *PPointingKernelPositions;
#endif // !defined(_TC_TYPE_20B39C3A_F540_49EF_8434_28702C07488B_INCLUDED_)

typedef struct _trkModuleParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} trkModuleParameter, *PtrkModuleParameter;

typedef struct _trkModuleInputs
{
	TrkMeanCoordinates MeanCoordinates;
	TrkPomTerms Terms;
	TimeInfo TimeInfo;
	SlaParams SlaParams;
} trkModuleInputs, *PtrkModuleInputs;

typedef struct _trkModuleOutputs
{
	PointingKernelPositions CcsDeterministic;
} trkModuleOutputs, *PtrkModuleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_trkModuleInputs 0
#define ADI_trkModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
