<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="FB_NOTT_CRYO_INTERLOCKS" Id="{f5954335-cc13-4f49-8d9a-cbf7fe5d073b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_NOTT_CRYO_INTERLOCKS
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
		stat:		T_NOTT_STAT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_NOTT_CRYO_INTERLOCKS">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>