<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="FB_NOTT_MOTOR" Id="{5c8e8201-f39f-4718-9355-022ac104e455}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_NOTT_MOTOR EXTENDS FB_MOTOR
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
SUPER^();]]></ST>
    </Implementation>
    <LineIds Name="FB_NOTT_MOTOR">
      <LineId Id="10" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>