<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="FB_HMI_COOLERS" Id="{300d24ef-5c84-476c-8ab8-e4343af29535}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HMI_COOLERS EXTENDS FB_HMI_COMPONENT
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HMI_COOLERS">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>