///////////////////////////////////////////////////////////////////////////////
// trkparamsClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "trkparamsClassFactory.h"
#include "trkparamsServices.h"
#include "trkparamsVersion.h"
#include "trkParams.h"

BEGIN_CLASS_MAP(CtrkparamsClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_trkparamsCtrkParams, SRVNAME_TRKPARAMS "!CtrkParams", CtrkParams)
///</AutoGeneratedContent>
END_CLASS_MAP()

CtrkparamsClassFactory::CtrkparamsClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_TRKPARAMS)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(trkparams));
#endif //defined(TCDBG_UNIT_VERSION)
}

