<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="FB_NOTT_CO2_PRESSURE_CONTROL" Id="{ed2768eb-fec2-4f1e-903e-ca4d99e4a92f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_NOTT_CO2_PRESSURE_CONTROL
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	stat:		T_NOTT_STAT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_NOTT_CO2_PRESSURE_CONTROL">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>