<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="FB_HMI_RP_BRANCH_B" Id="{7c5bc2ea-77c5-49ad-9d1d-b72de3dd2d7c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HMI_RP_BRANCH_B EXTENDS FB_HMI_COMPONENT
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HMI_RP_BRANCH_B">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>