<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="FB_HMI_PRESSURES" Id="{f4fcd2cf-5351-4206-a9d2-944f16ec2a39}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HMI_PRESSURES EXTENDS FB_HMI_COMPONENT
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HMI_PRESSURES">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>