# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\fys-lab-ivs\Documents\Git\NottControl\NOTTControl\camera\parametersdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(253, 212)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 233, 201))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cb_presets = QtWidgets.QComboBox(self.widget)
        self.cb_presets.setObjectName("cb_presets")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_presets)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.edit_param_nr = QtWidgets.QLineEdit(self.widget)
        self.edit_param_nr.setObjectName("edit_param_nr")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_param_nr)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cb_parametertype = QtWidgets.QComboBox(self.widget)
        self.cb_parametertype.setObjectName("cb_parametertype")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_parametertype)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.edit_param_value = QtWidgets.QLineEdit(self.widget)
        self.edit_param_value.setObjectName("edit_param_value")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_param_value)
        self.button_get = QtWidgets.QPushButton(self.widget)
        self.button_get.setObjectName("button_get")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.button_get)
        self.button_set = QtWidgets.QPushButton(self.widget)
        self.button_set.setObjectName("button_set")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.button_set)
        self.label_feedback = QtWidgets.QLabel(self.widget)
        self.label_feedback.setText("")
        self.label_feedback.setObjectName("label_feedback")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.label_feedback)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Configure Parameters"))
        self.label_4.setText(_translate("Dialog", "Presets:"))
        self.label.setText(_translate("Dialog", "Parameter nr."))
        self.label_2.setText(_translate("Dialog", "Parameter type:"))
        self.label_3.setText(_translate("Dialog", "Value:"))
        self.button_get.setText(_translate("Dialog", "Get"))
        self.button_set.setText(_translate("Dialog", "Set"))
