<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_CRYO_TEMPERATURES" Id="{da3db0a8-7555-40f7-8a65-0f78d8431970}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CRYO_TEMPERATURES
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_CRYO_TEMPERATURES">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>