<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FUN_HOMING" Id="{c8dc9b93-a2c3-4e83-ba78-da6aa376e3ce}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FUN_HOMING : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FUN_HOMING">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>