<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_HOMMING" Id="{e2c004dd-dc4e-4568-9713-155f8b0cd73c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_HOMMING
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG_HOMMING">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>